"""Trains the first version of the confidence model on synthetic bootstrap labels.

No real human review outcomes exist yet (Week 9+ starts collecting them — see
docs/confidence-labelling-guide.md), so this builds training examples by running the
REAL retrieval pipeline against the 120 synthetic historical tickets already seeded in
the database (data/seed_synthetic_tickets.py): each ticket's own subject+description is
used as a query against its own (already-correct) department, exactly the way the live
extract -> classify -> route -> retrieve -> draft pipeline scores a real ticket. Only
the LABEL is synthetic (synthetic_labels.py's documented formula) — every feature value
is computed from real retrieval against the real embeddings table. See
docs/confidence-model.md for the full write-up, including honest limitations (no
attachment-bearing tickets in this bootstrap set, so ocr_confidence has zero variance
in training — see that doc before trusting this feature's learned weight).

Usage (from backend/): uv run python ../ai/confidence/train.py
Requires the `ai` extra and a running, migrated, seeded database (departments, the 120
synthetic historical tickets, and their embeddings — see data/README.md).
"""

import asyncio
import json
import random
import sys
from pathlib import Path

import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split

BACKEND_DIR = Path(__file__).resolve().parents[2] / "backend"
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))
AI_EMBEDDINGS_DIR = Path(__file__).resolve().parents[1] / "embeddings"
if str(AI_EMBEDDINGS_DIR) not in sys.path:
    sys.path.insert(0, str(AI_EMBEDDINGS_DIR))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from sqlalchemy import select  # noqa: E402
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine  # noqa: E402

from app.config import settings  # noqa: E402
from app.models import Department, Ticket  # noqa: E402

from retrieve import retrieve_evidence  # noqa: E402
from features import FEATURE_NAMES, compute_features  # noqa: E402
from synthetic_labels import simulate_outcome  # noqa: E402

SEED = 42
ARTIFACTS_DIR = Path(__file__).resolve().parent / "artifacts"
METRICS_FILE = Path(__file__).resolve().parents[2] / "docs" / "confidence-metrics.md"


async def _build_dataset() -> list[tuple[list[float], bool]]:
    engine = create_async_engine(settings.database_url)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    rng = random.Random(SEED)
    rows: list[tuple[list[float], bool]] = []

    async with session_factory() as db:
        departments = {d.id: d.name for d in await db.scalars(select(Department))}
        tickets = list(
            await db.scalars(
                select(Ticket).where(Ticket.status == "closed", Ticket.department_id.is_not(None))
            )
        )

        for ticket in tickets:
            department_name = departments.get(ticket.department_id)
            query_text = f"{ticket.subject}\n\n{ticket.description}"
            # k=6, then drop the ticket's own embedding row (it's in the same table
            # it's being embedded against, so it would otherwise match itself at
            # distance ~0 — an unrealistic freebie no live ticket ever gets).
            evidence = await retrieve_evidence(db, query_text, ticket.department_id, k=6)
            evidence = [item for item in evidence if item.source_id != ticket.id][:5]

            features = compute_features(evidence, ocr_confidence=None, department_name=department_name)
            label = simulate_outcome(features, rng)
            rows.append((features.to_vector(), label))

    await engine.dispose()
    return rows


def _report_to_markdown(report: dict, auc: float, n_train: int, n_test: int, coefficients: dict) -> str:
    lines = [
        "# Confidence model — initial evaluation",
        "",
        "Generated by `ai/confidence/train.py`. See "
        "[confidence-model.md](confidence-model.md) for the feature engineering "
        "rationale and what these numbers do and don't mean.",
        "",
        f"Trained on {n_train} examples, evaluated on {n_test} held-out examples "
        "(synthetic bootstrap labels — see confidence-model.md).",
        "",
        "| Class | Precision | Recall | F1 | Support |",
        "|---|---|---|---|---|",
    ]
    for label, stats in report.items():
        if label in ("accuracy", "macro avg", "weighted avg"):
            continue
        name = "success" if label == "1" else "failure"
        lines.append(
            f"| {name} | {stats['precision']:.2f} | {stats['recall']:.2f} | "
            f"{stats['f1-score']:.2f} | {int(stats['support'])} |"
        )
    macro = report["macro avg"]
    lines.append(
        f"| **macro avg** | {macro['precision']:.2f} | {macro['recall']:.2f} | "
        f"{macro['f1-score']:.2f} | {int(macro['support'])} |"
    )
    lines.append(f"\n**Accuracy:** {report['accuracy']:.2f}  \n**ROC-AUC:** {auc:.3f}")

    lines.append("\n## Learned feature coefficients\n")
    lines.append("| Feature | Coefficient |")
    lines.append("|---|---|")
    for name, coef in coefficients.items():
        lines.append(f"| `{name}` | {coef:+.3f} |")

    return "\n".join(lines)


def main() -> None:
    rows = asyncio.run(_build_dataset())
    X = np.array([r[0] for r in rows])
    y = np.array([int(r[1]) for r in rows])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=SEED, stratify=y
    )

    model = LogisticRegression(max_iter=1000, class_weight="balanced")
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    probabilities = model.predict_proba(X_test)[:, 1]
    report = classification_report(y_test, predictions, output_dict=True, zero_division=0)
    auc = roc_auc_score(y_test, probabilities)

    print(f"=== Confidence model ({len(X_train)} train / {len(X_test)} test) ===")
    print(classification_report(y_test, predictions, zero_division=0))
    print(f"ROC-AUC: {auc:.3f}")

    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, ARTIFACTS_DIR / "confidence_model.joblib")

    coefficients = dict(zip(FEATURE_NAMES, model.coef_[0].tolist()))
    with (ARTIFACTS_DIR / "metrics.json").open("w", encoding="utf-8") as f:
        json.dump(
            {
                "n_train": len(X_train),
                "n_test": len(X_test),
                "report": report,
                "roc_auc": auc,
                "coefficients": coefficients,
            },
            f,
            indent=2,
        )

    METRICS_FILE.write_text(
        _report_to_markdown(report, auc, len(X_train), len(X_test), coefficients) + "\n", encoding="utf-8"
    )
    print(f"\nSaved model to {ARTIFACTS_DIR}/confidence_model.joblib, metrics to {METRICS_FILE}")


if __name__ == "__main__":
    main()
