"""resolved ticket embeddings

Revision ID: 9384c16eb31c
Revises: 0002
Create Date: 2026-08-30 19:06:54.244049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('ticket_id', sa.UUID(), nullable=True))
    op.alter_column('embeddings', 'knowledge_base_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_embeddings_ticket_id'), 'embeddings', ['ticket_id'], unique=False)
    op.create_foreign_key(
        'embeddings_ticket_id_fkey', 'embeddings', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE'
    )
    op.create_check_constraint('ck_embeddings_exactly_one_source', 'embeddings', '(knowledge_base_id IS NOT NULL) != (ticket_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_embeddings_exactly_one_source', 'embeddings', type_='check')
    op.drop_constraint('embeddings_ticket_id_fkey', 'embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_embeddings_ticket_id'), table_name='embeddings')
    op.alter_column('embeddings', 'knowledge_base_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('embeddings', 'ticket_id')
    # ### end Alembic commands ###
